### ISSUE TITLE
UART Streaming for EVAL-ADXL355-PMDZ data

### ISSUE THREAD

**Issue by namsancow** [analogdevicesinc/EVAL-ADICUP360#25]
I tested the example of ADuCM360_demo_adxl355_pmdz.
And I succeeded to get the value of EVAL-ADXL355-PMDZ !!!
However, I must tap <Enter> button to receive the next data.
Is there any example to get the data continuously?

**Comment by adrimbarean** [comment]
Hello,

Seems like there is no option to get data continuously based on the code [here](https://github.com/analogdevicesinc/EVAL-ADICUP360/blob/master/projects/ADuCM360_demo_adxl355_pmdz/src/main.c#L182). But you can comment out the `if` and it will give data as fast as it comes.

These types of questions are much better suited for the [support forum](https://ez.analog.com/circuits_from_the_lab). Please post them there from now on.

Regards,
Andrei
