### ISSUE TITLE
EVAL-ADXL355-PMDZ ODR Rate

### ISSUE THREAD

**Issue by namsancow** [analogdevicesinc/EVAL-ADICUP360#26]
Is there any example to apply ODR rate of EVAL-ADXL355-PMDZ for ADICUP360 ?
I found the "Sensors_Pack" in https://github.com/analogdevicesinc/EVAL-ADICUP3029.
However, I could not find the proper example to apply ODR rate in https://github.com/analogdevicesinc/EVAL-ADICUP3029.
If there is some example, It would be of great help.

**Comment by adrimbarean** [comment]
Hello,

I cannot find any example to apply ODR to the device, but do check out the [wiki page](https://wiki.analog.com/resources/eval/user-guides/eval-adicup360/reference_designs/demo_adxl355) for this project and post a question on the [support forum](https://ez.analog.com/circuits_from_the_lab). There is a good chance the answer there will be better as there are more people watching and answering.

Regards,
Andrei
